Renamed repo on GitHub to grscheller/home
- the submodule can't share its root with the super project
  - as a submodule, it will get "mounted" as home/
  - config represents ~/.config
  - home represents ~/
- besides it is not just bash
- updated internals and README.md to reflect name change

diff --git a/homeInstall b/homeInstall
--- a/homeInstall
+++ b/homeInstall
@@ -9,16 +9,16 @@
 #    - remove items
 #
 
-export scriptName=bashInstall
+export scriptName=homeInstall
 
 ### Setup
 
 XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
-BASH_GIT_REPO="${BASH_GIT_REPO:=$HOME/devel/bash}"
+HOME_GIT_REPO="${HOME_GIT_REPO:=$HOME/devel/home}"
 umask 0022
 
-cd "$BASH_GIT_REPO" || {
-   printf "\\nError: Failed to cd into '%s'\\n" "$BASH_GIT_REPO"
+cd "$HOME_GIT_REPO" || {
+   printf "\\nError: Failed to cd into '%s'\\n" "$HOME_GIT_REPO"
    return 1
 }
 
